### ISSUE TITLE
Invalid image

### ISSUE THREAD

**Issue by Amro77** [shahednasser/quran-extension-firefox#1]
<img width="1091" alt="Screen Shot 2021-03-12 at 10 26 30 AM" src="https://user-images.githubusercontent.com/49485234/110913145-6c591600-831d-11eb-86a9-8d74d25b95fd.png">
invlid

**Comment by shahednasser** [comment]
Hello thank you for reporting this. As the images are randomly fetched from Unsplash (since it's free) some images may be problematic. That's why you can click on the report icon at the top left so that this image will not appear again. Sorry for the inconvenience and thank you for reporting this!
