### ISSUE TITLE
Why is the extension removed from Firefox addons store?

### ISSUE THREAD

**Issue by nasikshafeek** [shahednasser/quran-extension-firefox#2]
Salams,
This is exactly what I was searching for! Thanks for the work.

I note that the extension is removed from the Firefox addons store, do you happen to know why and will it be released by any other means?

**Comment by shahednasser** [comment]
Salam @kisanme , unfortunately Firefox found an issue in the code that requires resolving. It's not major, however, it's hard maintaining both the Chrome and Firefox extensions. As the Chrome extension has more users I decided to focus on it for now.

I hope you understand!
